DROP TABLE buyouts CASCADE;
DROP TABLE cities CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE payments CASCADE;
DROP TABLE pick_points CASCADE;
DROP TABLE plans CASCADE;
DROP TABLE streets CASCADE;
DROP TABLE users CASCADE;